type Query {
    products: [Product!]!
    categories: [Category!]!
}

#Int Float String Boolean ID
type Product {
    id: ID!
    name: String!
    description: String!
    price: Float!
    category: Category
}

type Category {
    id: ID!
    name: String!
    products: [Product!]!
}