export const productsData = [
  {
    id: 'product1',
    name: 'T-Shirt',
    description: 'A comfortable cotton t-shirt',
    price: 19.99,
    categoryId: 'clothing',
  },
  {
    id: 'product2',
    name: 'Jeans',
    description: 'Classic denim jeans',
    price: 49.99,
    categoryId: 'clothing',
  },
  {
    id: 'product3',
    name: 'Sneakers',
    description: 'Sporty sneakers for casual wear',
    price: 39.99,
    categoryId: 'footwear',
  },
  {
    id: 'product4',
    name: 'Backpack',
    description: 'Stylish and spacious backpack',
    price: 29.99,
    categoryId: 'accessories',
  },
  {
    id: 'product5',
    name: 'Dress',
    description: 'Elegant evening dress',
    price: 79.99,
    categoryId: 'clothing',
  },
  {
    id: 'product6',
    name: 'Watch',
    description: 'Sleek and modern wristwatch',
    price: 99.99,
    categoryId: 'accessories',
  },
  {
    id: 'product7',
    name: 'Shorts',
    description: 'Comfortable summer shorts',
    price: 24.99,
    categoryId: 'clothing',
  },
  {
    id: 'product8',
    name: 'Sunglasses',
    description: 'UV protection sunglasses',
    price: 14.99,
    categoryId: 'accessories',
  },
  {
    id: 'product9',
    name: 'Sweater',
    description: 'Warm and cozy sweater',
    price: 34.99,
    categoryId: 'clothing',
  },
  {
    id: 'product10',
    name: 'Handbag',
    description: 'Chic handbag for any occasion',
    price: 59.99,
    categoryId: 'accessories',
  },
];